[platformio]
src_dir=firmware/smart-entryway-energy-saver
[env:esp32dev]
platform=espressif32@6.10.0
board=esp32dev
framework=arduino
monitor_speed=115200
lib_deps=
  adafruit/Adafruit INA219@1.2.3
  knolleary/PubSubClient@2.8
